// Core workflow commands
module.exports = [
  {
    name: 'status',
    aliases: ['st', 'ss'],
    description: 'Show repository status',
    category: 'core',
    subcategory: 'statusChanges',
    handler: require('./status'),
  },
  {
    name: 'status-short',
    aliases: ['s'],
    description: 'Show short one-line status',
    category: 'core',
    subcategory: 'statusChanges',
    handler: require('./status-short'),
  },
  {
    name: 'diff',
    aliases: [],
    description: 'Show changes between commits, branches, or files',
    category: 'core',
    subcategory: 'statusChanges',
    handler: require('./diff'),
  },
  {
    name: 'info',
    aliases: [],
    description: 'Quick repository overview',
    category: 'core',
    subcategory: 'statusChanges',
    handler: require('./info'),
  },
  {
    name: 'add',
    aliases: [],
    description: 'Stage files for commit',
    category: 'core',
    subcategory: 'commit',
    handler: require('./add'),
  },
  {
    name: 'commit',
    aliases: ['ci', 'save'],
    description: 'Create commits with conventional format',
    category: 'core',
    subcategory: 'commit',
    handler: require('./commit'),
  },
  {
    name: 'log',
    aliases: [],
    description: 'View commit history',
    category: 'core',
    subcategory: 'history',
    handler: require('./log'),
  },
  {
    name: 'show',
    aliases: [],
    description: 'Show commit details and changes',
    category: 'core',
    subcategory: 'history',
    handler: require('./show'),
  },
];
