// Utility commands
module.exports = [
  {
    name: 'help',
    aliases: [],
    description: 'Show help for commands',
    category: 'advanced',
    subcategory: 'help',
    handler: require('./help'),
  },
  {
    name: 'config',
    aliases: [],
    description: 'Git configuration management',
    category: 'gettingStarted',
    handler: require('./config'),
  },
  {
    name: 'notify',
    aliases: [],
    description: 'Manage desktop notifications',
    category: 'gettingStarted',
    handler: require('./notify'),
  },
  {
    name: 'history',
    aliases: [],
    description: 'Show recent commands executed',
    category: 'advanced',
    subcategory: 'commandHistory',
    handler: require('./history'),
  },
  {
    name: 'template',
    aliases: [],
    description: 'Manage commit message templates',
    category: 'advanced',
    subcategory: 'customization',
    handler: require('./template'),
  },
  {
    name: 'preset',
    aliases: [],
    description: 'Manage workflow presets',
    category: 'advanced',
    subcategory: 'customization',
    handler: require('./preset'),
  },
  {
    name: 'theme',
    aliases: [],
    description: 'Customize color theme',
    category: 'advanced',
    subcategory: 'customization',
    handler: require('./theme'),
  },
  {
    name: 'examples',
    aliases: [],
    description: 'Show usage examples',
    category: 'advanced',
    subcategory: 'help',
    handler: require('./examples'),
  },
  {
    name: 'tutorial',
    aliases: [],
    description: 'Interactive walkthrough',
    category: 'advanced',
    subcategory: 'help',
    handler: require('./tutorial'),
  },
  {
    name: 'undo',
    aliases: ['reset'],
    description: 'Undo operations and reflog browser',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./undo'),
  },
  {
    name: 'revert',
    aliases: [],
    description: 'Revert commits',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./revert'),
  },
  {
    name: 'stash',
    aliases: [],
    description: 'Stash management (save/restore changes)',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./stash'),
  },
  {
    name: 'stash-all',
    aliases: [],
    description: 'Stash all changes including untracked files',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./stash-all'),
  },
  {
    name: 'restore',
    aliases: [],
    description: 'Restore files from index or commit',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./restore'),
  },
  {
    name: 'restore-backup',
    aliases: [],
    description: 'Restore from backup branch',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./restore-backup'),
  },
  {
    name: 'bisect',
    aliases: [],
    description: 'Binary search to find bug-introducing commit',
    category: 'advanced',
    subcategory: 'undo',
    handler: require('./bisect'),
  },
  {
    name: 'rm',
    aliases: [],
    description: 'Remove files from git',
    category: 'advanced',
    subcategory: 'fileOps',
    handler: require('./rm'),
  },
  {
    name: 'mv',
    aliases: [],
    description: 'Move/rename files',
    category: 'advanced',
    subcategory: 'fileOps',
    handler: require('./mv'),
  },
  {
    name: 'clean',
    aliases: [],
    description: 'Remove untracked files',
    category: 'advanced',
    subcategory: 'fileOps',
    handler: require('./clean'),
  },
  {
    name: 'tag',
    aliases: [],
    description: 'Tag management (list, create, delete)',
    category: 'advanced',
    subcategory: 'tagging',
    handler: require('./tag'),
  },
  {
    name: 'tag-push',
    aliases: [],
    description: 'Create and push tag in one flow',
    category: 'advanced',
    subcategory: 'tagging',
    handler: require('./tag-push'),
  },
  {
    name: 'tag-delete',
    aliases: [],
    description: 'Delete tag locally and remotely',
    category: 'advanced',
    subcategory: 'tagging',
    handler: require('./tag-delete'),
  },
  {
    name: 'conflicts',
    aliases: [],
    description: 'List all conflicted files',
    category: 'advanced',
    subcategory: 'inspection',
    handler: require('./conflicts'),
  },
  {
    name: 'resolve',
    aliases: [],
    description: 'Open conflicted file in editor and stage after resolution',
    category: 'advanced',
    subcategory: 'inspection',
    handler: require('./resolve'),
  },
  {
    name: 'add-pattern',
    aliases: [],
    description: 'Stage files matching a pattern',
    category: 'advanced',
    subcategory: 'fileOps',
    handler: require('./add-pattern'),
  },
  {
    name: 'diff-preview',
    aliases: [],
    description: 'Preview changes before committing',
    category: 'dailyWork',
    subcategory: 'commit',
    handler: require('./diff-preview'),
  },
  {
    name: 'preview-diff',
    aliases: [],
    description: 'Preview diffs',
    category: 'dailyWork',
    subcategory: 'commit',
    handler: require('./preview-diff'),
  },
  {
    name: 'hooks',
    aliases: [],
    description: 'List all git hooks in repository',
    category: 'advanced',
    subcategory: 'inspection',
    handler: require('./hooks'),
  },
  {
    name: 'state',
    aliases: [],
    description: 'Show current repository state',
    category: 'advanced',
    subcategory: 'inspection',
    handler: require('./state'),
  },
];
