// Branching & merging commands
module.exports = [
  {
    name: 'branch',
    aliases: ['br', 'co'],
    description: 'Branch management (list, create, delete)',
    category: 'workingWithOthers',
    subcategory: 'branching',
    handler: require('./branch'),
  },
  {
    name: 'checkout',
    aliases: [],
    description: 'Checkout branches or restore files',
    category: 'workingWithOthers',
    subcategory: 'branching',
    handler: require('./checkout'),
  },
  {
    name: 'switch',
    aliases: ['sw'],
    description: 'Switch branches (modern alternative to checkout)',
    category: 'workingWithOthers',
    subcategory: 'branching',
    handler: require('./switch'),
  },
  {
    name: 'merge',
    aliases: [],
    description: 'Merge branches',
    category: 'workingWithOthers',
    subcategory: 'branching',
    handler: require('./merge'),
  },
  {
    name: 'rebase',
    aliases: [],
    description: 'Rebase operations',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./rebase'),
  },
  {
    name: 'cherry-pick',
    aliases: [],
    description: 'Apply commits from another branch',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./cherry-pick'),
  },
  {
    name: 'mergetool',
    aliases: ['mt'],
    description: 'Launch merge tool to resolve conflicts',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./mergetool'),
  },
  {
    name: 'merge-continue',
    aliases: [],
    description: 'Continue merge after resolving conflicts',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./merge-continue'),
  },
  {
    name: 'merge-abort',
    aliases: [],
    description: 'Abort merge operation',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./merge-abort'),
  },
  {
    name: 'branch-clean',
    aliases: [],
    description: 'Delete merged branches interactively',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./branch-clean'),
  },
  {
    name: 'branch-rename',
    aliases: [],
    description: 'Rename branch locally and remotely',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./branch-rename'),
  },
  {
    name: 'branch-compare',
    aliases: [],
    description: 'Show differences between two branches',
    category: 'advanced',
    subcategory: 'advancedBranching',
    handler: require('./branch-compare'),
  },
];
