// Remote operations commands
module.exports = [
  {
    name: 'push',
    aliases: ['ps', 'up'],
    description: 'Push to remote',
    category: 'workingWithOthers',
    subcategory: 'remote',
    handler: require('./push'),
  },
  {
    name: 'pull',
    aliases: ['pl', 'down'],
    description: 'Fetch and merge from remote',
    category: 'workingWithOthers',
    subcategory: 'remote',
    handler: require('./pull'),
  },
  {
    name: 'fetch',
    aliases: [],
    description: 'Fetch from remote',
    category: 'workingWithOthers',
    subcategory: 'remote',
    handler: require('./fetch'),
  },
  {
    name: 'sync',
    aliases: [],
    description: 'Synchronize (pull + rebase + push)',
    category: 'workingWithOthers',
    subcategory: 'remote',
    handler: require('./sync'),
  },
  {
    name: 'remote',
    aliases: [],
    description: 'Manage remote repositories',
    category: 'workingWithOthers',
    subcategory: 'remote',
    handler: require('./remote'),
  },
  {
    name: 'remote-set-url',
    aliases: [],
    description: 'Update remote URL interactively',
    category: 'advanced',
    subcategory: 'utilities',
    handler: require('./remote-set-url'),
  },
  {
    name: 'create-pr',
    aliases: ['pr'],
    description: 'Create pull request/merge request',
    category: 'advanced',
    subcategory: 'utilities',
    handler: require('./create-pr'),
  },
  {
    name: 'clear-cache',
    aliases: [],
    description: 'Clear all caches',
    category: 'advanced',
    subcategory: 'utilities',
    handler: require('./clear-cache'),
  },
];
